{
    'name': 'Kawiil Base',
    'summary': 'This module adds the configurations required for the Kawiil Motors training exercise production database.',
    'license': 'OPL-1',
    'category': 'Kawiil/Kawiil',
    'author': 'Odoo, Inc.',
    'website': 'https://github.com/odoo-trainings/kawiil-base/',
    'version': '1.0.0',
    'application': True,
    'depends': ['sale_management', 'mrp', 'contacts', 'hr'],
    'data': [
        'data/res_company_data.xml',
        'data/res_users_data.xml',
        'data/hr_data.xml',
        'data/res_config_settings_data.xml',
        'data/res_partner_data.xml',
        'data/product_data.xml',
        'data/sale_order_data.xml',
    ],
}
